### ISSUE TITLE
NAs in Allophones

### ISSUE THREAD

**Issue by bambooforest** [phoible/phoible#80] opened 2015-04-20 20:12 UTC
Not sure if this is an issue @drammock but I'm in the middle of the aspiration cleaning so wanted to file a quick issue as not to forget what I came across (Source, LanguageCode, Phoneme, Allophone):

ra	awa	cçʰ	NA
ra	ben	cçʰ	NA
ra	bft	cçʰ	NA
ra	bkk	cçʰ	NA
ra	bns	cçʰ	NA
ra	cdn	cçʰ	NA
gm	xuu	bʰ	bʰ
ph	ahk	cçʰ	cçʰ
spa	aka	cçʰ	cçʰ

**Comment by drammock** [comment] 2015-04-21 03:58
That is a feature, not a bug.  `NA` means "this resource had no info about allophones at all", where as an empty string means "this resource listed allophones for some phonemes, but this particular phoneme didn't have an entry".  If you want to discuss revising this convention, feel free to re-open and convince me :)

**Comment by bambooforest** [comment] 2015-04-21 07:36
reopening because this is smart and it should be noted in the conventions, which i will do.

**Comment by drammock** [comment] 2015-04-21 07:48
ok, just make sure to re-close once that's done.  Also, can we change the
conventions document from PDF to plain text or (better yet) markdown?

**Comment by drammock** [comment] 2015-04-24 11:58
the information about `NA` in allophone column is now recorded [on the wiki](https://github.com/phoible/phoible/wiki/About-PHOIBLE), so I'm closing this issue.

**Closed by drammock** 2015-04-24 11:58 UTC
